name: bananinha_studio
description: "A simple image editor integrated with Google Gemini 2.5 Flash Image (Nano Banana)."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/RotaFeita/rotafeita_mobile

version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: ^3.35.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
